eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: springboot-web
  cloud:
    config:
      label: master
      profile: dev
#      uri: http://localhost:8751/
      discovery:
         enabled: true
         serviceId: config-server
management:
  security:
    enabled: false
server:
  port: 8080