eureka:
  client:
    serviceUrl:
      defaultZone: http://10.201.250.239:8761/eureka/
spring:
  application:
    name: springboot-web
  cloud:
    config:
      label: master
      profile: dev
#      uri: http://10.201.250.239:8751/
      discovery:
         enabled: true
         serviceId: config-server
  

  

  
  
